# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/SharedProjects/bert_111717 - Copy/bert_111717.cache/wt} [current_project]
set_property parent.project_path {C:/SharedProjects/bert_111717 - Copy/bert_111717.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_output_repo {c:/SharedProjects/bert_111717 - Copy/bert_111717.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/s883g970/Desktop/bert_110317/5b_bitstream.coe
read_vhdl -library xil_defaultlib {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd}}
add_files {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/design_1.bd}}
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/design_1_c_counter_binary_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_1_0/design_1_util_ds_buf_1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/design_1_ooc.xdc}}]
set_property is_locked true [get_files {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/sources_1/bd/design_1/design_1.bd}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/constrs_1/new/constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/SharedProjects/bert_111717 - Copy/bert_111717.srcs/constrs_1/new/constraints.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
